[target.aarch64-apple-darwin]
# rustflags = ["-Ctarget-cpu=native"]

[target.x86_64-unknown-linux-gnu]
# The following configs are in an increasing performance order for x86_64.
# rustflags = ["-Ctarget-feature=+avx2"]
# rustflags = ["-Ctarget-feature=+avx512vl,+avx512f"]
# rustflags = ["-Ctarget-feature=+avx512vl,+avx512f,+avx512bw,+avx512cd,+avx512dq"]
# rustflags = ["-Ctarget-feature=+avx512f"]
# rustflags = ["-Ctarget-cpu=native"]

[target.x86_64-unknown-x86_64-pc-windows-msvc-gnu]
# The following configs are in an increasing performance order for x86_64.
# rustflags = ["-Ctarget-feature=+avx2"]
# rustflags = ["-Ctarget-feature=+avx512vl,+avx512f"]
# rustflags = ["-Ctarget-feature=+avx512vl,+avx512f,+avx512bw,+avx512cd,+avx512dq"]
# rustflags = ["-Ctarget-feature=+avx512f"]
# rustflags = ["-Ctarget-cpu=native"]
